let tagLocation = "location"
let tagCustomLocation = "customLocation"
let tagInOrOut = "inOrOut"
let tagPerson = "person"
let tagVisitor = "visitor"
let tagNameList = "nameList"
let tagLocationList = "locationList"
